"""initial Sprint 1 schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-19

Sprint 1 creates the whole schema from the SQLAlchemy metadata (single source of
truth) so models and migration cannot drift. Subsequent sprints add incremental,
autogenerated migrations (render_as_batch is on for SQLite-safe ALTERs).
"""
from __future__ import annotations

from alembic import op

from app.db import Base
import app.models  # noqa: F401  (register tables on Base.metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
